EstadoReal/Models/Contrato.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace EstadoReal.Models
{
    public class Contrato
    {
        [Key]
        public int IdContrato { get; set; }
        [Required]
        public DateTime InicioContrato { get; set; }
        [Required]
        public DateTime FinContrato { get; set; }
        [Required]
        public decimal Deudas { get; set; }
        [Required]
        public int IdInquilino { get; set; }
        [Required]
        public int IdInmueble { get; set; }

        public byte EstadoContrato { get; set; }

        [ForeignKey("IdInquilino")]
        public Inquilino Inquilino { get; set; }

        [ForeignKey("IdInmueble")]
        public Inmueble Inmueble { get; set; }

    }
}

EstadoReal/Controllers/ContratoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using EstadoReal.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace EstadoReal.Controllers
{
    [Authorize(Policy = "Empleado")]
    public class ContratoController : Controller
    {
        private readonly IRepositorioContrato repositorio;
        private readonly IRepositorioEmpleado empleadoRepo;
        private readonly IRepositorioInquilino inquilino;
        private readonly IRepositorioInmueble inmueble;
        private readonly IRepositorioPago pago;

        public ContratoController(IRepositorioContrato repositorio, IRepositorioEmpleado empleadoRepo, IRepositorioInquilino inquilino, IRepositorioInmueble inmueble, IRepositorioPago pago)
        {
            this.repositorio = repositorio;
            this.empleadoRepo = empleadoRepo;
            this.inquilino = inquilino;
            this.inmueble = inmueble;
            this.pago = pago;
        }

        // GET: Contrato
        public ActionResult Index()
        {

            var identity = (ClaimsIdentity)User.Identity;
            var empleadoNombre = identity.Name;
            IEnumerable<Claim> claims = identity.Claims;

            ViewBag.empleado = empleadoRepo.ObtenerPorCorreo(empleadoNombre);

            var lista = repositorio.ObtenerTodos();
            if (TempData.ContainsKey("Id"))
                ViewBag.Id = TempData["Id"];
            return View(lista);
        }

        // GET: Contrato/Details/5
        public ActionResult Details(int id)
        {
            try
            {
                var contrato = repositorio.ObtenerPorId(id);
                ViewBag.InquilinoTodos = inquilino.ObtenerTodos();
                ViewBag.InmuebleTodos = inmueble.ObtenerTodos();
                return View(contrato);
            }
            catch (Exception e)
            {
                ViewBag.Error = e.Message;
                ViewBag.StackTrate = e.StackTrace;
                return View();
            }
        }

        // GET: Contrato/Create
        public ActionResult Create()
        {
            ViewBag.InquilinoTodos = inquilino.ObtenerTodos();
            ViewBag.InmuebleTodos = inmueble.ObtenerTodos();
            return View();
        }

        // POST: Contrato/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Contrato contrato)
        {
            ViewBag.id = contrato.IdContrato;

            try
            {
                if (ModelState.IsValid)
                {
                    repositorio.Alta(contrato);
                    ViewBag.InquilinoTodos = inquilino.ObtenerTodos();
                    ViewBag.InmuebleTodos = inmueble.ObtenerTodos();
                    ViewBag.MensajeError = null;
                    ViewBag.Exito = "Contrato creado con exito";
                    return View();
                }
                else
                    ViewBag.InquilinoTodos = inquilino.ObtenerTodos();
                    ViewBag.InmuebleTodos = inmueble.ObtenerTodos();
                    ViewBag.MensajeError = "Uh no, mandaste uno o mas campos vacíos.";
                    return View();
            }
            catch (Exception ex)
            {
                ViewBag.InquilinoTodos = inquilino.ObtenerTodos();
                ViewBag.InmuebleTodos = inmueble.ObtenerTodos();
                ViewBag.Error = ex.Message;
                ViewBag.StackTrate = ex.StackTrace;
                ViewBag.MensajeError = "No sabemos que pasó pero hiciste algo mal seguro";
                return View();
            }
        }

        // GET: Contrato/Edit/5
        public ActionResult Edit(int id)
        {
            ViewBag.id = id;
            ViewBag.InquilinoTodos = inquilino.ObtenerTodos();
            ViewBag.InmuebleTodos = inmueble.ObtenerTodos();
            var contrato = repositorio.ObtenerPorId(id);
            return View(contrato);
        }

        // POST: Contrato/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Contrato contrato)
        {
            ViewBag.id = contrato.IdContrato;
            try
            {
                if (ModelState.IsValid)
                {
                    repositorio.Modificacion(contrato);
                    var con = repositorio.ObtenerPorId(contrato.IdContrato);
                    ViewBag.MensajeError = null;
                    ViewBag.Exito = "Contrato editado con exito";
                    ViewBag.InquilinoTodos = inquilino.ObtenerTodos();
                    ViewBag.InmuebleTodos = inmueble.ObtenerTodos();
                    return View(con);
                }
                else
                    ViewBag.InquilinoTodos = inquilino.ObtenerTodos();
                    ViewBag.InmuebleTodos = inmueble.ObtenerTodos();
                    var cont = repositorio.ObtenerPorId(contrato.IdContrato);
                    ViewBag.MensajeError = "Uh no, mandaste uno o mas campos vacíos.";
                    return View(cont);
            }
            catch (Exception ex)
            {
                ViewBag.InquilinoTodos = inquilino.ObtenerTodos();
                ViewBag.InmuebleTodos = inmueble.ObtenerTodos();
                ViewBag.Error = ex.Message;
                ViewBag.StackTrate = ex.StackTrace;
                var cont = repositorio.ObtenerPorId(contrato.IdContrato);
                ViewBag.MensajeError = "No sabemos que pasó pero hiciste algo mal seguro";
                return View(cont);
            }
        }

        // GET: Contrato/Delete/5
        public ActionResult Eliminar(int id)
        {
            try
            {
                var contrato = repositorio.ObtenerPorId(id);
                return View(contrato);
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                ViewBag.StackTrae = ex.StackTrace;
                return View();
            }
        }

        // POST: Contrato/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Eliminar(Contrato contrato)
        {
            try
            {
                repositorio.Baja(contrato.IdContrato);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                ViewBag.StackTrae = ex.StackTrace;
                return View();
            }
        }
        // GET: Contrato/Buscar/5
        public ActionResult DateFilter()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DateFilter(Contrato contrato)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var contratos = repositorio.BuscarEntreFechas(contrato.InicioContrato, contrato.FinContrato);

                    if (contratos.Count() == 0)
                    {
                        ViewBag.Error = "No se encontraron resultados";
                        return View();
                    }
                    else
                    {
                        ViewBag.Error = "";
                        return View(contratos);
                    }
                } else
                {
                    ViewBag.Error = "No se encontraron resultados";
                    return View();
                }
                    
            }
            catch (Exception ex)
            {
                ViewBag.Error = "No se encontraron resultados";
                ViewBag.StackTrae = ex.StackTrace;
                return View();
            }
        }

        // GET: Contrato/Buscar/5
        public ActionResult ListPagos(int id)
        {
            ViewBag.MisPagos = pago.ObtenerPagosPorContrato(id);
            return View();
        }
    }
}

EstadoReal/Controllers/PagoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using EstadoReal.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace EstadoReal.Controllers
{
    [Authorize(Policy = "Empleado")]
    public class PagoController : Controller
    {
        private readonly IRepositorio<Pago> repositorio;
        private readonly IRepositorioEmpleado empleadosRepo;
        private readonly IRepositorioContrato contrato;

        public PagoController(IRepositorio<Pago> repositorio, IRepositorioEmpleado empleadosRepo, IRepositorioContrato contrato)
        {
            this.repositorio = repositorio;
            this.empleadosRepo = empleadosRepo;
            this.contrato = contrato;
        }

        // GET: Pago
        public ActionResult Index()
        {
            var identity = (ClaimsIdentity)User.Identity;
            var empleadoNombre = identity.Name;
            IEnumerable<Claim> claims = identity.Claims;

            ViewBag.empleado = empleadosRepo.ObtenerPorCorreo(empleadoNombre);

            var lista = repositorio.ObtenerTodos();
            if (TempData.ContainsKey("Id"))
                ViewBag.Id = TempData["Id"];
            return View(lista);
        }

        // GET: Pago/Details/5
        public ActionResult Details(int id)
        {
            try
            {
                var pago = repositorio.ObtenerPorId(id);
                return View(pago);
            }
            catch (Exception e)
            {
                ViewBag.Error = e.Message;
                ViewBag.StackTrate = e.StackTrace;
                return View();
            }
        }

        // GET: Pago/Create
        public ActionResult Create()
        {
            ViewBag.ContratosTodos = contrato.ObtenerTodos();
            return View();
        }

        // POST: Pago/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Pago pago)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    repositorio.Alta(pago);
                    ViewBag.ContratosTodos = contrato.ObtenerTodos();
                    ViewBag.MensajeError = null;
                    ViewBag.Exito = "Realizado con éxito";
                    return View();
                }
                else
                    ViewBag.ContratosTodos = contrato.ObtenerTodos();
                ViewBag.MensajeError = "Parece que cometiste un error";
                    return View();
            }
            catch (Exception ex)
            {
                ViewBag.ContratosTodos = contrato.ObtenerTodos();
                ViewBag.Error = ex.Message;
                ViewBag.StackTrate = ex.StackTrace;
                ViewBag.MensajeError = "No sabemos que pasó pero seguro hiciste algo mal.";
                return View();
            }
        }

        // GET: Pago/Edit/5
        public ActionResult Edit(int id)
        {
            ViewBag.id = id;
            var pago = repositorio.ObtenerPorId(id);
            ViewBag.ContratosTodos = contrato.ObtenerTodos();
            return View(pago);
        }

        // POST: Pago/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Pago pago)
        {
            ViewBag.id = pago.IdPago;

            try
            {
                if (ModelState.IsValid)
                {
                    
                    repositorio.Modificacion(pago);
                    ViewBag.ContratosTodos = contrato.ObtenerTodos();
                    var pagoRec = repositorio.ObtenerPorId(pago.IdPago);
                    ViewBag.MensajeError = null;
                    ViewBag.Exito = "Realizado con éxito";
                    return View(pagoRec);
                }
                else
                    ViewBag.ContratosTodos = contrato.ObtenerTodos();
                    var pagoRe= repositorio.ObtenerPorId(pago.IdPago);
                    ViewBag.MensajeError = "Parece que cometiste un error";
                    return View(pagoRe);
            }
            catch (Exception ex)
            {
                ViewBag.ContratosTodos = contrato.ObtenerTodos();
                ViewBag.Error = ex.Message;
                ViewBag.StackTrate = ex.StackTrace;
                var pagoRe = repositorio.ObtenerPorId(pago.IdPago);
                ViewBag.MensajeError = "No sabemos que pasó pero seguro hiciste algo mal.";
                return View(pagoRe);
            }
        }

        // GET: Pago/Delete/5
        public ActionResult Eliminar(int id)
        {
            try
            {
                var pago = repositorio.ObtenerPorId(id);
                return View(pago);
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                ViewBag.StackTrae = ex.StackTrace;
                return View();
            }
        }

        // POST: Pago/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Eliminar(Pago pago)
        {
            try
            {
                repositorio.Baja(pago.IdPago);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                ViewBag.StackTrae = ex.StackTrace;
                return View();
            }
        }
    }
}

EstadoReal/Views/Contrato/Create.cshtml
@model EstadoReal.Models.Contrato

@{
    ViewData["Title"] = "Create";
}

<link href="~/css/EmpleadoCrear.css" rel="stylesheet" type="text/css" />

<div class="contenedor-nav">
    <nav>
        <input type="checkbox" id="menu" class="hidden" />
        <label class="logo-Volver" for="menu"><img src="~/img/VolverIcon.png" alt="Volver" /></label>
        <label class="logo-1" for="menu"><img src="~/img/MenuBlack.png" alt="Menu" /></label>
        <div class="logo-2"><a asp-action="Index"><img src="~/img/ERIcon1Black.png" alt="Estado Real" /></a></div>
        <div class="logo-3"><a asp-controller="Home" asp-action="Logout"><img src="~/img/SalirIcon.png" alt="Cerrar Sesion" /></a></div>
    </nav>
</div>

<div class="nav-display" id="nav">
    <div><a asp-controller="Propietario" asp-action="index">Propietarios</a></div>
    <div><a asp-controller="Inmueble" asp-action="index">Inmuebles</a></div>
    <div><a asp-controller="Inquilino" asp-action="index">Inquilinos</a></div>
    <div><a asp-controller="Contrato" asp-action="index">Contratos</a></div>
    <div><a asp-controller="Pago" asp-action="index">Pagos</a></div>
    <div><a asp-controller="Empleado" asp-action="Index">Configuracion</a></div>
    <div><a asp-controller="Home" asp-action="Logout">Salir</a></div>
</div>

<div class="contenedor-formulario-registrar">

    <div class="contenedor-bienvenida">
        <h2>Registar nuevo contrato: No te olvides de llenar todos los campos.</h2>
    </div>
    <div class="contenedor-crear">
        <div class="imagen-usuario"> <img src="~/img/User2.png" alt="crear empleado" /></div>
        <div></div>
        <p>Crear contrato</p>
    </div>
    <div class="contenedor-formulario">
        <form asp-action="Create" class="formulario">
            <div class="contendor-f1">
                <div class="form-group">
                    <label asp-for="InicioContrato" class="control-label"></label>
                    <input class="form-control" type="date" name="InicioContrato"/>
                    <span asp-validation-for="InicioContrato" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="FinContrato" class="control-label"></label>
                    <input class="form-control" type="date" name="FinContrato" />
                    <span asp-validation-for="FinContrato" class="text-danger"></span>
                </div>
            </div>
            <div class="contendor-f1">
                <div class="form-group">
                    <label asp-for="Deudas" class="control-label"></label>
                    <input asp-for="Deudas" class="form-control" placeholder="Deudas" />
                    <span asp-validation-for="Deudas" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label class="control-label">Inquilino</label>
                    <select class="form-control" name="IdInquilino">
                        @foreach (var item in (IList<Inquilino>)ViewBag.InquilinoTodos)
                        {
                            @:<option value="@item.IdInquilino">@(item.Nombre + " " + item.Apellido)</option>
                        }
                    </select>
                    <span asp-validation-for="IdInquilino" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label class="control-label">Inmueble</label>
                    <select class="form-control" name="IdInmueble">
                        @foreach (var item in (IList<Inmueble>)ViewBag.InmuebleTodos)
                        {
                            @:<option value="@item.IdInmueble">@(item.Direccion)</option>
                        }
                    </select>
                    <span asp-validation-for="IdInmueble" class="text-danger"></span>
                </div>
            </div>
            <div class="contendor-f1">
                <div class="form-group ultimo">
                    <a asp-action="Index">Cancelar</a>
                    <input type="submit" value="Crear" class="btn-1" />
                </div>
            </div>
            <div>
                @if (ViewBag.MensajeError == null)
                {
                    <p style="color: #6D9B65;"> @ViewBag.Exito </p>
                }
                else
                {
                    <p class="mensaje-error"> @ViewBag.MensajeError</p>
                }
            </div>
        </form>
    </div>
</div>

<script>

    let check = document.getElementById("menu");
    let nav = document.getElementById("nav");
    let contenido = document.getElementById("mostrar");

    check.addEventListener('click', () => {
        if (check.checked) {
            nav.style.display = "flex";
            contenido.style.display = "none";
        } else {
            nav.style.display = "none";
            contenido.style.display = "flex";
        }
    });

</script>

EstadoReal/Views/Contrato/DateFilter.cshtml
@model IEnumerable<EstadoReal.Models.Contrato>

@{
    ViewData["Title"] = "DateFilter";
}

<link href="~/css/EmpleadoCrear.css" rel="stylesheet" type="text/css" />

<div class="contenedor-nav">
    <nav>
        <input type="checkbox" id="menu" class="hidden" />
        <label class="logo-Volver" for="menu"><img src="~/img/VolverIcon.png" alt="Volver" /></label>
        <label class="logo-1" for="menu"><img src="~/img/MenuBlack.png" alt="Menu" /></label>
        <div class="logo-2"><a asp-action="Index"><img src="~/img/ERIcon1Black.png" alt="Estado Real" /></a></div>
        <div class="logo-3"><a asp-controller="Home" asp-action="Logout"><img src="~/img/SalirIcon.png" alt="Cerrar Sesion" /></a></div>

    </nav>
</div>

<div class="nav-display" id="nav">
    <div><a asp-controller="Propietario" asp-action="index">Propietarios</a></div>
    <div><a asp-controller="Inmueble" asp-action="index">Inmuebles</a></div>
    <div><a asp-controller="Inquilino" asp-action="index">Inquilinos</a></div>
    <div><a asp-controller="Contrato" asp-action="index">Contratos</a></div>
    <div><a asp-controller="Pago" asp-action="index">Pagos</a></div>
    <div><a asp-controller="Empleado" asp-action="Index">Configuracion</a></div>
    <div><a asp-controller="Home" asp-action="Logout">Salir</a></div>
</div>

<div class="contenedor-formulario-registrar">

    <div class="contenedor-bienvenida">
        <h2>Busqueda de contratos por fechas</h2>
    </div>

    <div class="contenedor-formulario">
        <form asp-action="DateFilter" class="formulario">
            <div class="contendor-f1">
                <div class="form-group">
                    <label class="control-label">InicioContrato </label>
                    <input class="form-control" type="date" name="InicioContrato" />
                    <span class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label class="control-label">FinContrato</label>
                    <input class="form-control" type="date" name="FinContrato" />
                    <span class="text-danger"></span>
                </div>
            </div>
            <div class="contendor-f1">
                <div class="form-group ultimo">
                    <a asp-action="Index">Volver</a>
                    <input type="submit" value="Buscar" class="btn-1" />
                </div>
            </div>
        </form>
        @if (Model != null)
        {
            <div class="contenedor-bienvenida">
                <h2>Resultados de la busqueda:</h2>
            </div>
            @foreach (var item in Model)
            {
                <div class="contendor-f1">
                    <div class="form-group">
                        <p class="control-label">Inicio Contrato: @item.InicioContrato</p>
                    </div>
                    <div class="form-group">
                        <p class="control-label">Fin Contrato: @item.FinContrato</p>
                    </div>
                    <div class="form-group">
                        <p class="control-label">Id Contrato: @item.IdContrato</p>
                    </div>
                    <div class="form-group">
                        @Html.ActionLink("ver más", "Details", new { id = item.IdContrato })
                    </div>
                </div>
            }
        }

        <p class="control-label">@ViewBag.Error</p>

    </div>
</div>



<script>

    let check = document.getElementById("menu");
    let nav = document.getElementById("nav");
    let contenido = document.getElementById("mostrar");

    check.addEventListener('click', () => {
        if (check.checked) {
            nav.style.display = "flex";
            contenido.style.display = "none";
        } else {
            nav.style.display = "none";
            contenido.style.display = "flex";
        }
    });

</script>

EstadoReal/Views/Contrato/Details.cshtml
@model EstadoReal.Models.Contrato

@{
    ViewData["Title"] = "Details";
}

<link href="~/css/EmpleadoDetalles.css" type="text/css" rel="stylesheet" />

<div class="contenedor-nav">
    <nav>
        <input type="checkbox" id="menu" class="hidden" />
        <label class="logo-Volver" for="menu"><img src="~/img/VolverIcon.png" alt="Volver" /></label>
        <label class="logo-1" for="menu"><img src="~/img/MenuBlack.png" alt="Menu" /></label>
        <div class="logo-2"><a asp-action="Index"><img src="~/img/ERIcon1Black.png" alt="Estado Real" /></a></div>
        <div class="logo-3"><a asp-controller="Home" asp-action="Logout"><img src="~/img/SalirIcon.png" alt="Cerrar Sesion" /></a></div>
    </nav>
</div>

<div class="nav-display" id="nav">
    <div><a asp-controller="Propietario" asp-action="index">Propietarios</a></div>
    <div><a asp-controller="Inmueble" asp-action="index">Inmuebles</a></div>
    <div><a asp-controller="Inquilino" asp-action="index">Inquilinos</a></div>
    <div><a asp-controller="Contrato" asp-action="index">Contratos</a></div>
    <div><a asp-controller="Pago" asp-action="index">Pagos</a></div>
    <div><a asp-controller="Empleado" asp-action="Index">Configuracion</a></div>
    <div><a asp-controller="Home" asp-action="Logout">Salir</a></div>
</div>

<div class="contenedor-formulario-registrar">

    <div class="contenedor-bienvenida">
        <h2>Detalles del Contrato</h2>
    </div>

    <div class="contenedor-formulario">
        <div class="contendor-f1">
            <div class="form-group">
                <p>@Html.DisplayNameFor(model => model.InicioContrato)</p>
            </div>
            <div class="form-group data">
                <p>@Html.DisplayFor(model => model.InicioContrato)</p>
            </div>
            <div class="form-group">
                <p>@Html.DisplayNameFor(model => model.FinContrato)</p>
            </div>
            <div class="form-group data">
                <p>@Html.DisplayFor(model => model.FinContrato)</p>
            </div>
        </div>
        <div class="contendor-f1">
            <div class="form-group">
                <p>@Html.DisplayNameFor(model => model.Deudas)</p>
            </div>
            <div class="form-group data">
                <p>@Html.DisplayFor(model => model.Deudas)</p>
            </div>
            <div class="form-group">
                <p>Inquilino</p>
            </div>
            <div class="form-group data">
                @foreach (var item in (IList<Inquilino>)ViewBag.InquilinoTodos)
                {
                    if (item.IdInquilino == Model.IdInquilino)
                    {
                        <p>@(item.Nombre + " " + item.Apellido)</p>
                    }
                }
                <span asp-validation-for="IdInquilino" class="text-danger"></span>
            </div>
            <div class="form-group">
                <p>Inmueble</p>
            </div>
            <div class="form-group data">
                @foreach (var item in (IList<Inmueble>)ViewBag.InmuebleTodos)
                {
                    if (item.IdInmueble == Model.IdInmueble)
                    {
                        <p>@(item.Direccion)</p>
                    }
                }
                <span asp-validation-for="IdInquilino" class="text-danger"></span>
            </div>
        </div>
        <div class="contendor-f1">
            <div class="form-group">
                @Html.ActionLink("Ver Pagos", "ListPagos", new { id = Model.IdContrato })
            </div>
        </div>
        <div class="contendor-f1">
            <div class="form-group ultimo">
                <a asp-action="Index">Volver</a>
                @Html.ActionLink("editar", "Edit", new { id = Model.IdContrato })
            </div>
        </div>
    </div>
    <!--asp-route-id="(Arroba)Model.IdContrato"-->
</div>

<script>

    let check = document.getElementById("menu");
    let nav = document.getElementById("nav");
    let contenido = document.getElementById("mostrar");

    check.addEventListener('click', () => {
        if (check.checked) {
            nav.style.display = "flex";
            contenido.style.display = "none";
        } else {
            nav.style.display = "none";
            contenido.style.display = "flex";
        }
    });

</script>

EstadoReal/Views/Contrato/Eliminar.cshtml
@model EstadoReal.Models.Contrato

@{
    ViewData["Title"] = "Delete";
}

<link href="~/css/EmpleadoDetalles.css" type="text/css" rel="stylesheet" />

<div class="contenedor-nav">
    <nav>
        <input type="checkbox" id="menu" class="hidden" />
        <label class="logo-Volver" for="menu"><img src="~/img/VolverIcon.png" alt="Volver" /></label>
        <label class="logo-1" for="menu"><img src="~/img/MenuBlack.png" alt="Menu" /></label>
        <div class="logo-2"><a asp-action="Index"><img src="~/img/ERIcon1Black.png" alt="Estado Real" /></a></div>
        <div class="logo-3"><a asp-controller="Home" asp-action="Logout"><img src="~/img/SalirIcon.png" alt="Cerrar Sesion" /></a></div>
    </nav>
</div>

<div class="nav-display" id="nav">
    <div><a asp-controller="Propietario" asp-action="index">Propietarios</a></div>
    <div><a asp-controller="Inmueble" asp-action="index">Inmuebles</a></div>
    <div><a asp-controller="Inquilino" asp-action="index">Inquilinos</a></div>
    <div><a asp-controller="Contrato" asp-action="index">Contratos</a></div>
    <div><a asp-controller="Pago" asp-action="index">Pagos</a></div>
    <div><a asp-controller="Empleado" asp-action="Index">Configuracion</a></div>
    <div><a asp-controller="Home" asp-action="Logout">Salir</a></div>
</div>

<div class="contenedor-formulario-registrar">

    <div class="contenedor-bienvenida">
        <h2>¿Está seguro de borrar este contrato?</h2>
    </div>

    <div class="contenedor-formulario">
        <div class="contendor-f1">
            <div class="form-group">
                <p>@Html.DisplayNameFor(model => model.InicioContrato)</p>
            </div>
            <div class="form-group data">
                <p>@Html.DisplayFor(model => model.InicioContrato)</p>
            </div>
            <div class="form-group">
                <p>@Html.DisplayNameFor(model => model.FinContrato)</p>
            </div>
            <div class="form-group data">
                <p>@Html.DisplayFor(model => model.FinContrato)</p>
            </div>
        </div>
        <div class="contendor-f1">
            <div class="form-group">
                <p>@Html.DisplayNameFor(model => model.Deudas)</p>
            </div>
            <div class="form-group data">
                <p>@Html.DisplayFor(model => model.Deudas)</p>
            </div>
            <div class="form-group">
                <p>@Html.DisplayNameFor(model => model.IdInquilino)</p>
            </div>
            <div class="form-group data">
                <p>@Html.DisplayFor(model => model.IdInquilino)</p>
            </div>
            <div class="form-group">
                <p>@Html.DisplayNameFor(model => model.IdInmueble)</p>
            </div>
            <div class="form-group data">
                <p>@Html.DisplayFor(model => model.IdInmueble)</p>
            </div>
        </div>
        <div class="contendor-f1">
            <div class="form-group ultimo">
                <form asp-action="Delete">
                    <a asp-action="Index">Volver</a>
                    <input type="hidden" name="IdContrato" readonly value="@Html.DisplayFor(model => model.IdContrato)" />
                    <input type="submit" value="borrar" class="btn-1" />
                </form>
            </div>
        </div>
    </div>

</div>

<script>

    let check = document.getElementById("menu");
    let nav = document.getElementById("nav");
    let contenido = document.getElementById("mostrar");

    check.addEventListener('click', () => {
        if (check.checked) {
            nav.style.display = "flex";
            contenido.style.display = "none";
        } else {
            nav.style.display = "none";
            contenido.style.display = "flex";
        }
    });

</script>